### ISSUE TITLE
Request shortcode feature, for easy custom placement.

### ISSUE THREAD

**Issue by Jieiku** [gonzomir/minimal-share-buttons#3]
This is a request for the shortcode feature. It allows for easy custom placement of the social buttons.

currently I am using a workaround with "widget shortcode" and "code snippets" plugin:

```
function addSocials() {
echo do_shortcode('[widget id="minimal_share_buttons-2"]');
}
add_action('woocommerce_share','addSocials');
```

having shortcode would make it so this workaround is no longer needed.

**Comment by gonzomir** [comment]
I just release version 1.4 of the plugin that includes `[msb_share]` shortcode. The title of the output widget can be controlled with the `title` attribute like this: `[msb_share title="Share this now!"]`.
