### ISSUE TITLE
Additional class field in the widget

### ISSUE THREAD

**Issue by atanasantonov** [gonzomir/minimal-share-buttons#4]
Hi Great Gonzo! Want to share the idea to add an additional class field in administrative panel when placing widget. Thanks!

**Comment by gonzomir** [comment]
Oh, why am I seeing this just now? Where would you lake that class added? Adding additional class to every button is easy, but adding it to the widget itself is not.

It appears that adding additional class to the widget's container is not trivial, as the widget's render method doesn't have access to the variables, used to build the `before_widget` part of the widget attributes, it only gets the resulting string. And themes can use more complex stuff there, making simple text replacements risky.

**Comment by atanasantonov** [comment]
I'm seeing this now.. Yes ok, maybe it is not so good idea. Actually another issue I've opened is just adding a class to the buttons.

**Comment by gonzomir** [comment]
I'm closing this for now, if the need for this surfaces again, I'll give it a second thought.
