### ISSUE TITLE
Social identifier to button

### ISSUE THREAD

**Issue by atanasantonov** [gonzomir/minimal-share-buttons#7]
Great Gonzo thank you for your great plugin!

It will be nice to include a class identifying each button in future release. That way you can change the color of each button for example.

Best,
Atanas

**Comment by gonzomir** [comment]
In v1.6 I've added the social network class with a `msb-` prefix, and also added a filter that allows completely changing the classes of the buttons. Let me know if that works for your use case.

**Comment by atanasantonov** [comment]
Great!
